WHITE = "#f5f5f5"
BLACK = "#252525"
FONT_NAME = "Roboto Condensed"

TO_AVOID = ['csv']

EXTENSION = {
    "png": "images",
    "jpeg": "images",
    "jpg": "images",
    "gif": "images",
    "bmp": "images",
    "tiff": "images",
    "txt": "documents",
    "pdf": "documents",
    "doc": "documents",
    "docx": "documents",
    "odt": "documents",
    "xls": "documents",
    "xlsx": "documents",
    "ppt": "documents",
    "pptx": "documents",
    "mp3": "audio",
    "wav": "audio",
    "mp4": "video",
    "avi": "video",
    "mkv": "video",
    "mov": "video",
    "zip": "archives",
    "rar": "archives",
    "7z": "archives",
    "tar": "archives",
    "gz": "archives",
    "py": "code",
    "svg": "images",
    "html": "documents",
    "js": "code",
    "css": "code",
    "xml": "documents",
    "json": "code",
    "java": "code",
    "cpp": "code",
    "h": "code",
    "sql": "code",
    "php": "code",
    "asp": "code",
    "rb": "code",
    "pl": "code",
    "go": "code",
    "swift": "code",
    "bat": "code",
    "ini": "code",
    "log": "documents",
    "md": "documents",
    "yaml": "code",
    "epub": "ebooks",
    "mobi": "ebooks",
    "ics": "calendars",
    "iso": "disk_images",
    "img": "disk_images",
    "flac": "audio",
    "ogg": "audio",
    "aac": "audio",
    "flv": "video",
    "webm": "video",
    "swf": "video",
    "deb": "archives",
    "rpm": "archives",
    "exe": "executables",
    "dll": "executables",
    "xmind": "images",
    "pub": "documents",
    "psd": "images",
    "ai": "documents",
    "dxf": "documents",
    "mov": "video",
    "avi": "video",
    "wmv": "video",
    "c": "code",
    "cs": "code",
    "bat": "code",
    "sh": "code",
    "jar": "code",
    "apk": "executables",
    "bak": "archives",
    "bak": "archives",
    "bmp": "images",
    "raw": "images",
    "dng": "images",
    "eps": "images"
}

